"""Add slug

Revision ID: dd6efd5f6c6e
Revises: be421f075a32
Create Date: 2026-09-07 03:17:04.472440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd6efd5f6c6e'
down_revision: Union[str, Sequence[str], None] = 'be421f075a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_column('posts', 'slug')
    # ### end Alembic commands ###
